### ISSUE TITLE
device stuck at 0,0,0.0002625

### ISSUE THREAD

**Issue by HennieLP** [ESPresense/ESPresense-companion#17]
but get in status form multible stations
![grafik](https://user-images.githubusercontent.com/65833107/205467612-e46ace32-dee3-4ff0-9d3a-b5af1ea807d3.png)

![grafik](https://user-images.githubusercontent.com/65833107/205467638-c40d5acb-851e-4ba2-b307-92b41cbfccca.png)

config 
``` 
# MQTT Connection, if empty will query and use hassio provided mqtt
mqtt:
  host:
  port: 1883
  ssl: false
  username:
  password:

# Bounds (x,y,z) of map in  meters
bounds: [[-1, -1, -1], [30, 30, 5]]
# How long before device considered stale
timeout: 30
# How long before device is considered away
away_timeout: 120

# Floors w/ the points to draw it in meters
floors:
  - name: First Floor
    z: 1 # Elevation in meters
    rooms:
      - name: Schlafen
        points:
          - [8.4, 9.80]
          - [8.4, 13.75]
          - [12.3, 13.75]
          - [12.3, 10.25]
          - [14.1, 10.25]
          - [14.1, 7.7] 
      - name: Bad_Hinten
        points:
          - [14.2, 7.65]
          - [19.2, 5]
          - [19.2, 10]
          - [14.2, 10]
      - name: Buero
        points:
          - [15.6, 10.40]
          - [19.2, 10.40]
          - [19.2, 13.55]
          - [15.6, 13.55]
      - name: Gang_hinten
        points:
          - [12.5, 10.45]
          - [15.45, 10.45]
          - [15.45, 13.55]
          - [12.5, 13.55]
      - name: Wohnzimmer
        points:
          - [9.6, 14]
          - [14, 14]
          - [14, 23.15]
          - [9.6, 23.15]
      - name: Bad_Vorne
        points:
          - [14.25, 14.15]
          - [16.20, 14.15]
          - [16.20, 16.5]
          - [14.25, 16.5]
      - name: Gang
        points:
          - [14.25, 16.7]
          - [16.20, 16.7]
          - [16.20, 20.2]
          - [14.25, 20.2]
      - name: Kueche
        points:
          - [16.5, 14.15]
          - [20.20, 14.15]
          - [20.20, 18.4]
          - [16.5, 18.4]
      - name: Henne
        points:
          - [16.5, 18.6]
          - [20.20, 18.6]
          - [20.20, 23]
          - [16.5, 23]
# Locations of espresense nodes in meters
nodes:
  - name: henne
    point: [20, 22.75, 1.87]
  - name: wohnzimmer2
    point: [13.98, 22.8, 0.2]
  - name: wohnzimmer
    point: [10.2, 14.51, 0.4]
  - name: gang
    point: [16.14, 18.3, 0.5]
  - name: bad_vorne
    point: [14.34, 15, 2]
  - name: kueche
    point: [16.55, 14.22, 2.3]
  - name: buero
    point: [18.75, 10.425, 0.1]

# Devices to track
devices:
  - name: "Henne_Handy_hps"
    id: irk:fb153e4e80d2d1a51bc91a8162e9fa71


```

version 0.1.11 and 0.1.10

**Comment by HennieLP** [comment]
answer to the get request 
```
[
   {
      "id":"irk:c52ab7dc6ff2a929bdfdc7b892f0ffc4",
      "name":null,
      "location":{
         "x":0,
         "y":0,
         "z":0.0003038765625
      },
      "reportedLocation":{
         "x":0,
         "y":0,
         "z":0
      },
      "nodes":{
         
      },
      "scale":1
   },
   {
      "id":"irk:9e2708b69fae70c7ccefff7512d09b4a",
      "name":null,
      "location":{
         "x":0,
         "y":0,
         "z":0.000545718647095484
      },
      "reportedLocation":{
         "x":0,
         "y":0,
         "z":0
      },
      "nodes":{
         
      },
      "scale":1
   },
   {
      "id":"irk:fb153e4e80d2d1a51bc91a8162e9fa71",
      "name":null,
      "location":{
         "x":0,
         "y":0,
         "z":0.0003693638609472656
      },
      "reportedLocation":{
         "x":0,
         "y":0,
         "z":0
      },
      "nodes":{
         
      },
      "scale":1
   }
]

```

**Comment by DTTerastar** [comment]
If you click on the black dot the nodes will show circles based on the distance to that device.  Can you show that pic?

**Comment by DTTerastar** [comment]
Nevermind, somehow you've never matched a node.  I'll add some logging for that.

**Comment by DTTerastar** [comment]
Did logging help you find the issue?

**Comment by HennieLP** [comment]
version 1.1.13 sadly nothing special in the logs 

```
[13:02:15 INF] Loading /config/espresense/config.yaml
[13:02:15 WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
[13:02:15 WRN] No XML encryptor configured. Key {8329cc39-da40-4ecd-90e2-ff90e7d2ae17} may be persisted to storage in unencrypted form.
[13:02:15 INF] Now listening on: http://[::]:8267
[13:02:15 INF] Application started. Press Ctrl+C to shut down.
[13:02:15 INF] Hosting environment: Production
[13:02:15 INF] Content root path: /App
[13:02:15 INF] Connecting to mqtt server at core-mosquitto:1883...

```

**Comment by DTTerastar** [comment]
Ok, well I guess I need a "stats" page or something like that to see if you're getting any messages at all.

Do you see "espresense/companion/status", "online" in mqtt explorer?

Can you verify subscribing to espresense/devices/# works?

**Comment by HennieLP** [comment]
espresense/companion/status was "offline" but after a restart its now "Online"

**Comment by HennieLP** [comment]
how can i verify subscribing to espresense/devices/# works ?

**Comment by HennieLP** [comment]
and now after some time the z cordinate in espresense/ips/apple:1005:9-4 is climing exponential to the sky curently 10000 after ca 20 sekonds 40000

**Comment by DTTerastar** [comment]
you can subscribe to just that via mqtt explorer

**Comment by HennieLP** [comment]
i testet it it subscribing works 

but devices are still stuck at 0,0
even after updating the addon and updating the config

**Comment by HennieLP** [comment]
Version 0.2.5 same problem
giving devices to Track an id dosent help 
sadly i dont know what to do anymore
my config:
```
# MQTT Connection, if empty will query and use hassio provided mqtt
mqtt:
  host:
  port: 1883
  ssl: false
  username:
  password:

# How long before device considered stale
timeout: 30
# How long before device is considered away
away_timeout: 120

# Floors w/ the points to draw it in meters
floors:
  - id: first
    name: First Floor
  # Bounds (x,y,z) of map in  meters
    bounds: [[-1, -1, 0], [30, 30, 5]]
    rooms:
      - name: Schlafen
        points:
          - [8.4, 9.80]
          - [8.4, 13.75]
          - [12.3, 13.75]
          - [12.3, 10.25]
          - [14.1, 10.25]
          - [14.1, 7.7] 
      - name: Bad_Hinten
        points:
          - [14.2, 7.65]
          - [19.2, 5]
          - [19.2, 10]
          - [14.2, 10]
      - name: Buero
        points:
          - [15.6, 10.40]
          - [19.2, 10.40]
          - [19.2, 13.55]
          - [15.6, 13.55]
      - name: Gang_hinten
        points:
          - [12.5, 10.45]
          - [15.45, 10.45]
          - [15.45, 13.55]
          - [12.5, 13.55]
      - name: Wohnzimmer
        points:
          - [9.6, 14]
          - [14, 14]
          - [14, 23.15]
          - [9.6, 23.15]
      - name: Bad_Vorne
        points:
          - [14.25, 14.15]
          - [16.20, 14.15]
          - [16.20, 16.5]
          - [14.25, 16.5]
      - name: Gang
        points:
          - [14.25, 16.7]
          - [16.20, 16.7]
          - [16.20, 20.2]
          - [14.25, 20.2]
      - name: Kueche
        points:
          - [16.5, 14.15]
          - [20.20, 14.15]
          - [20.20, 18.4]
          - [16.5, 18.4]
      - name: Henne
        points:
          - [16.5, 18.6]
          - [20.20, 18.6]
          - [20.20, 23]
          - [16.5, 23]
      - name: Family
        points:
          - [0, 0]
          - [0, 5.5]
          - [5.2, 5.5]
          - [5.2, 0]
          - [0, 0]

# Locations of espresense nodes in meters

nodes:
  - name: henne
    point: [20, 22.75, 1.87]
    floors: ["first"]
  - name: wohnzimmer2
    point: [13.98, 22.8, 0.2]
    floors: ["first"]
  - name: wohnzimmer
    point: [10.2, 14.51, 0.4]
    floors: ["first"]
  - name: gang
    point: [16.14, 18.3, 0.5]
    floors: ["first"]
  - name: bad_vorne
    point: [14.34, 15, 2]
    floors: ["first"]
  - name: kueche
    point: [16.55, 14.22, 2.3]
    floors: ["first"]
  - name: buero
    point: [18.75, 10.42, 0.1]
    floors: ["first"]

# Devices to track
devices:
  - name: Henne_Handy_hps
    id: Henne_Handy
  - name: Henne_apple_watch
    id: Henne_Watch


```
