### ISSUE TITLE
Add flipX and flipY config options

### ISSUE THREAD

**Issue by jimmyeao** [ESPresense/ESPresense-companion#253]
Im struggling to get my head around the floor layout, I think the issue is with my bounds, the map shown is flipped vertically:
This:

![image](https://github.com/ESPresense/ESPresense-companion/assets/5197831/4c2fdf2c-779d-4a3a-af8d-030302f73f7f)
should really be orientated like this
![image](https://github.com/ESPresense/ESPresense-companion/assets/5197831/909d9864-45f0-40cf-9fd3-91c966d44eb7)
 with some padding the left and right, but im not sure how to achieve this.
Also,I set the GPS coordinates to the most south westerly point, ie the "office" but very few devices are appearing in a room: 
![image](https://github.com/ESPresense/ESPresense-companion/assets/5197831/e51796f7-b921-408d-8bf1-f0b0622ddde6)
This is the yaml im using
```
 floors:
  - id: ground
    name: Ground Floor
    bounds:
      - - 0
        - 0
        - 0
      - - 29.58
        - 29.58
        - 6.76
    rooms:
      - name: office
        points:
          - - 0
            - 0
          - - 3
            - 0
          - - 3
            - 5.0
          - - 0
            - 5.00
          - - 0
            - 0
      - name: DiningRoom
        points:
          - - 14.47
            - 3.59
          - - 18.98
            - 3.59
          - - 18.98
            - 6.76
          - - 14.47
            - 6.76
          - - 14.47
            - 3.59
      - name: kitchen
        points:
          - - 18.96
            - 3.59
          - - 23.44
            - 3.59
          - - 23.44
            - 6.76
          - - 18.96
            - 6.76
          - - 18.96
            - 3.59
      - name: RearLounge
        points:
          - - 23.43
            - 2.95
          - - 25.75
            - 2.95
          - - 25.75
            - 6.76
          - - 23.43
            - 6.76
          - - 23.43
            - 2.95
      - name: Lounge
        points:
          - - 25.75
            - 1.26
          - - 29.58
            - 1.26
          - - 29.58
            - 6.78
          - - 25.75
            - 6.78
          - - 25.75
            - 1.26
      - name: BackHall
        points:
          - - 23.47
            - 0.78
          - - 25.75
            - 0.78
          - - 25.75
            - 2.95
          - - 23.47
            - 2.95
          - - 23.47
            - 0.78
      - name: Hall
        points:
          - - 25.75
            - 0.17
          - - 29.57
            - 0.17
          - - 29.57
            - 1.27
          - - 25.75
            - 1.27
          - - 25.75
            - 0.17
  - id: first
    name: first Floor
    bounds:
      - - 0
        - 0
        - 3.1
      - - 29.58
        - 6.78
        - 6.76
    rooms:
      - name: Ryan
        points:
          - - 2.9
            - 0
          - - 6.15
            - 0
          - - 6.15
            - 3.79
          - - 2.9
            - 3.79
          - - 2.9
            - 0
      - name: Bedroom
        points:
          - - 0
            - 0
          - - 2.89
            - 0
          - - 2.89
            - 3.78
          - - 0
            - 3.78
          - - 0
            - 0
```
