### ISSUE TITLE
Implement NearestNode localizer and allow it to be forced per floor

### ISSUE THREAD

**Issue by scaytrase** [ESPresense/ESPresense-companion#293]
Use case: I have multiple floors in my house (4) and I'm currently expirementing with companion on single one. Before I was using standalone espresense with range filtration to detect people in the room. I'd like to swtich entirely to companion but it requires at least 3 fixes for devices in order to be "located'. Which is not really possible while I haven't setup 20+ nodes (multifloor is not really possible here)

It would be great if I can keep for selected floor current config (for experimenting and testing config and new versions) but set other selected floors as "locate device at node coordinates as soon as this node is closest to devices and within node configured range"

i.e

```yaml
floors:
 - id: f2
   name: floor 2 
   lateralizer: nearest_node # (current whatever named as default)
   bounds: [[0, 0, 6], [12, 7, 8.8]]
   rooms: [] #

nodes:
- name: f2_bedroom
  point: [8, 0.10, 6.70]
  filter:
    range: 2.0 # (and\or configured via node settings in UI)
  floors: ["f2"]
```

I see some code related to that, but I'm not really sure whether it works at all and\or configurable per floor
