### ISSUE TITLE
Map-Scale

### ISSUE THREAD

**Issue by Schroeder0815** [ESPresense/ESPresense-companion#584]
Hi,

is there any possibility to change the scale of the Map?

in my map the X-axis has a scale of 1m and the Y-axis has a scale of 0.5m.
So my map is very large in Y-axis and it looks very ugly.

I‘ve searched in the config.yaml and the webinterface, but without any solution.

thanks a lot and best regards.
Schroeder

**Comment by supaeasy** [comment]
Most likely you set boundaries wrong. Maybe a comma instead of a dot?

**Comment by Schroeder0815** [comment]
Hi,

thanks for your answer, but I could not find any „.“ vs. „,“ failure.
Here is my ESPresense config.yaml (feel free to have a look):
```
# MQTT Connection, if empty will query and use hassio provided mqtt
mqtt:
  host: 192.168.xxx.xxx
  port: 1883
  ssl: false
  username: xxxxxx
  password: xxxxxx

# This gets added to the x,y,z to derive a gps location
gps:
  latitude: xx.xxxxxx
  longitude: xx.xxxxxx
  elevation: xx

# How long before device considered stale
timeout: 30
# How long before device is considered away
away_timeout: 60

optimization:
  enabled: true
  interval_secs: 3600
  limits:
    absorption_min: 2.5
    absorption_max: 3.5
    tx_ref_rssi_min: -70
    tx_ref_rssi_max: -50
    rx_adj_rssi_min: -15
    rx_adj_rssi_max: 20

weighting:
  algorithm: gaussian
  props:
    sigma: 0.10

# Floors w/ the points to draw it in meters
floors:
  - id: Erdgeschoss
    name: Erdgeschoss
    # Bounds (x,y,z) of map in meters
    bounds: [[0, 0, 0], [11.90, 5.25, 2.55]]
    rooms:
      - name: Wohnzimmer
        points:
          - [0.11, 0.22]
          - [0.11, 7.59]
          - [3.92, 7.59]
          - [3.92, 4.31]
          - [3.59, 4.31]
          - [3.59, 4.17]
          - [5.14, 4.17]
          - [5.14, 0.22]
      - name: Kueche
        points:
          - [0.11, 7.73]
          - [0.11, 11.68]
          - [2.585, 11.68]
          - [2.585, 7.73]
      - name: Flur
        points:
          - [2.665, 7.73]
          - [2.665, 11.68]
          - [4.19, 11.68]
          - [4.19, 7.73]
      - name: Gaeste WC
        points:
          - [4.27, 9.93]
          - [4.27, 11.68]
          - [5.14, 11.68]
          - [5.14, 9.93]
      - name: Abstellraum
        points:
          - [4.27, 7.73]
          - [4.27, 9.83]
          - [5.14, 9.83]
          - [5.14, 7.73]
      - name: Treppe
        points:
          - [3.92, 4.31]
          - [3.92, 7.59]
          - [5.14, 7.59]
          - [5.14, 4.31]
  - id: 1OG
    name: 1OG
    bounds: [[0, 0, 3.1], [11.90, 5.25, 5.65]]
    rooms:
      - name: xxx1Schlafzimmer
        points:
          - [0.11, 0.22]
          - [0.11, 5.91]
          - [2.935, 5.91]
          - [2.935, 0.22]
      - name: Schlafzimmer
        points:
          - [0.11, 5.99]
          - [0.11, 11.68]
          - [02.935, 11.68]
          - [2.935, 5.99]
      - name: Bad
        points:
          - [3.015, 7.73]
          - [3.015, 11.68]
          - [5.14, 11.68]
          - [5.14, 7.73]
      - name: Flur+Treppe
        points:
          - [3.015, 4.31]
          - [3.015, 7.59]
          - [5.14, 7.59]
          - [5.14, 4.31]
      - name: xxx Arbeitszimmer
        points:
          - [3.015, 0.22]
          - [3.015, 4.17]
          - [5.14, 4.17]
          - [5.14, 0.22]
  - id: 2OG
    name: 2OG
    bounds: [[0, 0, 5.85], [11.90, 5.25, 9.40]]
    rooms:
      - name: xxx2Schlafzimmer
        points:
          - [0.11, 0.22]
          - [0.11, 6.155]
          - [3.815, 6.155]
          - [3.815, 4.17]
          - [5.14, 4.17]
          - [5.14, 0.22]
      - name: Ankleidezimmer
        points:
          - [0.11, 6.265]
          - [0.11, 7.59]
          - [2.635, 7.59]
          - [2.635, 6.265]
      - name: Gaestezimmer
        points:
          - [0.11, 7.73]
          - [0.11, 11.68]
          - [5.14, 11.68]
          - [5.14, 7.73]
      - name: Flur+Treppe
        points:
          - [2.645, 7.59]
          - [5.14, 7.59]
          - [5.14, 4.31]
          - [3.915, 4.31]
          - [3.915, 6.265]
          - [2.645, 6.265]
  - id: Keller
    name: Keller
    bounds: [[0, 0, -0.20], [11.90, 5.25, -2.75]]
    rooms:
      - name: Werkstatt
        points:
          - [0.11, 0.22]
          - [0.11, 4.17]
          - [5.14, 4.17]
          - [5.14, 0.22]
      - name: Vorratsraum
        points:
          - [0.11, 4.27]
          - [0.11, 7.59]
          - [2.59, 7.59]
          - [2.59, 4.27]
      - name: Waschkueche
        points:
          - [0.11, 7.73]
          - [0.11, 11.68]
          - [5.14, 11.68]
          - [5.14, 7.73]
      - name: Flur+Treppe
        points:
          - [2.67, 4.31]
          - [2.67, 7.59]
          - [5.14, 7.59]
          - [5.14, 4.31]
  - id: outside
    name: Outside
    bounds: [[0, -9.0, 0], [5.25, 18.9, 15]]
    rooms:
      - name: Garten
        points:
          - [0, 0]
          - [5.25, -0.1]
          - [5.25, -6.0]
          - [0, -6.0]
      - name: Parkplatz
        points:
          - [0, 11.9]
          - [0, 18.9]
          - [5.25, 18.9]
          - [5.25, 11.9]

# Locations of espresense nodes in meters
nodes:
  - name: wohnzimmer
    point: [0.15, 2.22, 0.80]
    floors: ["Erdgeschoss", "Keller", "1OG"]
  - name: kueche
    points: [0.15, 11.50, 2.10]
    floors: ["Erdgeschoss", "Keller", "1OG"]
  - name: flureg
    point: [4.28, 9.6, 0.80]
    floors: ["Erdgeschoss", "Keller", "1OG"]
  - name: xxx1schlafzimmer
    point: [1.5, 5.86, 3.9]
    floors: ["1OG", "Erdgeschoss", "2OG"]
  - name: schlafzimmer
    point: [0.75, 11.68, 3.9]
    floors: ["1OG", "Erdgeschoss", "2OG"]
  - name: arbeitszimmer
    point: [5.04, 0.7, 3.9]
    floors: ["1OG", "Erdgeschoss", "2OG"]
  - name: xxx2schlafzimmer
    point: [4.14, 0.4, 5.9]
    floors: ["2OG", "1OG"]
  - name: gaestezimmer
    point: [5.04, 9.78, 5.9]
    floors: ["2OG", "1OG"]
  - name: werkstatt
    point: [4.14, 0.23, -1.75]
    floors: ["Keller", "Erdgeschoss"]
  - name: waschkueche
    point: [4.8, 11.68, -1.75]
    floors: ["Keller", "Erdgeschoss"]


# Devices to track
devices:
  - name: "*" # Track all named devices
  #- id: "tile:*" # Track all tiles
  - id: "irk:*" # Track all IRKs
  #- id: "watch:*"
  #- id: "phone:*"
  #- id: "wallet:*"
  #- id: "keys:*"
  #- id: "therm:*"
  #- id: "iBeacon:*"

```
