### ISSUE TITLE
Calibration only uses Rx RSSI adjustments

### ISSUE THREAD

**Issue by dxmnkd316** [ESPresense/ESPresense-companion#628]
I'm not sure if this is a bug or not.  

I recently added several more base stations to my house.  I set them up and waited for the calibration to run.  It ended up erasing all of the absorption numbers, setting them all to 3, and now it only adjusts Rx RSSI and only moderately successfully.

What would cause the calibration routine to do this?  It's been running for a couple days now and the absorption hasn't been touched?  I tried digging through the code a bit but I quickly get lost in the calibration sections.  

Thanks

**Comment by dxmnkd316** [comment]
Would still like to see a resolution/discussion on this.  Thanks!

**Comment by maxi1134** [comment]
What do you mean by "The calibration to run"?

Is there an automatic tool to do it?
I've been manually calibrating my whole setup.

**Comment by dxmnkd316** [comment]
> What do you mean by "The calibration to run"?
> 
> Is there an automatic tool to do it? I've been manually calibrating my whole setup.

This can probably be closed.  It took a couple of days but the automatic calibration eventually started updating the absorption as well.  I've dug deeper into the code since I submitted this and my understanding is that the calibration will try multiple ways to get a better solution:  Changing the Rx RSSI of the nodes AND changing the absorption.  If one or both give better solutions, it will take the best and apply that.  Since the Rx RSSI provided better solutions than absorption for those several days, the absorption just sat at whatever the default was.  

As to your question about what I meant, ESPresense will automatically calibrate your nodes to give the best results using known distances between nodes.  I find it works pretty good overall.  I've fine-tuned using manual calibration before, but I don't think it's necessarily worth the effort unless the automatic calibration is just not working for how your house and nodes are laid out.

To get it to work, you need to add something like this to your ESPresense config.yaml (not the HA configuration.yaml)

```
optimization:
  enabled: true
  interval_secs: 120
  max_snapshots: 300
  limits:
    absorption_min: 1.0
    absorption_max: 5
    tx_ref_rssi_min: -70
    tx_ref_rssi_max: -30
    rx_adj_rssi_min: -15
    rx_adj_rssi_max: 20

```

You can also use the ESPresense recommendation ([link](https://github.com/ESPresense/ESPresense-companion/blob/main/src/config.example.yaml))

```
optimization:
  enabled: true
  interval_secs: 3600
  limits:
    absorption_min: 2.5
    absorption_max: 3.5
    tx_ref_rssi_min: -70
    tx_ref_rssi_max: -50
    rx_adj_rssi_min: -15
    rx_adj_rssi_max: 20

```

The difference between my settings and the recommendation is that I have mine running the calibration every two minutes since I've been doing experimentation and the default is once an hour and the "width" of the absorption range it can apply from 2.5-->3.5 to my range of 1-->5.  I also changed the max_snapshots from the default of 60 but I don't think it's changed much and probably should just change it back.  I also haven't ever found the calibration to change the Tx RSSI for a node so I'm not sure that's useful either.
