### ISSUE TITLE
possible to configre individual wall thickness?

### ISSUE THREAD

**Issue by ecto1a2003** [ESPresense/ESPresense-companion#889]
is it possible to configure individual wall thickness and type? some of my walls don't actually exist and are just there to delineate rooms.

**Comment by DTTerastar** [comment]
How would you suggest updating the yaml?

**Comment by jonwilliams84** [comment]
Maybe use reference attenuation of common building materials and define each wall at room intersections.

E.g.
```
material_types:
  drywall:
    description: Standard drywall
    default_attenuation: 4.0
  concrete:
    description: Dense Concrete wall
    default_attenuation: 13.5
  thermalite:
    description: Thermalite wall
    default_attenuation: 7.0
  glass:
    description: Glass window/door
    default_attenuation: 2.0
  metal:
    description: Metal door or structure
    default_attenuation: 8.0
  osb_double:
    description: Double layer 18mm OSB
    default_attenuation: 12.0
  open:
    description: Open space/doorway
    default_attenuation: 0.0
    
walls:
- start: [4.37, 6]
  end: [4.37, 6.8]
  floor: ground
  room_names: [Kitchen]
  material: concrete
  attenuation: 13.5
- start: [4.37, 1.91]
  end: [0, 1.91]
  floor: ground
  room_names: [Garage]
  material: concrete
  attenuation: 13.5
- start: [4.09, 2.9]
  end: [1.9, 2.9]
  floor: first
  room_names: [Noah Bedroom]
  material: drywall
  attenuation: 4.0
- start: [6.23, 5.28]
  end: [6.23, 5.28]
  floor: first
  room_names: [Master Bedroom]
  material: drywall
  attenuation: 4.0
- start: [10.7, 5.71]
  end: [6.82, 5.71]
  floor: ground
  room_names: [Dining Room, Lounge]
  material: thermalite
  attenuation: 7.0
- start: [4.95, 7.54]
  end: [4.95, 7.54]
  floor: first
  room_names: [Airing Cupboard]
  material: drywall
  attenuation: 4.0
- start: [6.21, 5.28]
  end: [6.21, 5.89]
  floor: first
  room_names: [Spare Room Wardrobe]
  material: drywall
  attenuation: 4.0
- start: [4.37, 3.24]
  end: [1.95, 3.24]
  floor: ground
  room_names: [Office, Garage]
  material: osb_double
  attenuation: 12.0
- start: [1.91, 4.49]
  end: [1.91, 3.24]
  floor: ground
  room_names: [Garage]
  material: osb_double
  attenuation: 12.0
- start: [1.95, 3.24]
  end: [1.95, 6.8]
  floor: ground
  room_names: [Office]
  material: osb_double
  attenuation: 12.0
- start: [6.82, 6]
  end: [6.82, 1.9]
  floor: ground
  room_names: [Hall]
  material: concrete
  attenuation: 13.5
- start: [4.37, 4.5]
  end: [4.37, 6]
  floor: ground
  room_names: [Hall]
  material: concrete
  attenuation: 13.5
- start: [1.95, 6.72]
  end: [0, 6.72]
  floor: ground
  room_names: [Utility, New Utility]
  material: concrete
  attenuation: 13.5
- start: [1.95, 4.49]
  end: [0, 4.49]
  floor: ground
  room_names: [New Utility, Garage]
  material: osb_double
  attenuation: 12.0
- start: [1.9, 6.0]
  end: [4.09, 6.0]
  floor: first
  room_names: [Noah Bedroom, Sophie Bedroom]
  material: drywall
  attenuation: 4.0
- start: [6.82, 0]
  end: [6.82, 5.71]
  floor: ground
  room_names: [Lounge]
  material: concrete
  attenuation: 13.5
- start: [1.9, 6.0]
  end: [1.9, 6.0]
  floor: first
  room_names: [Noah Bedroom]
  material: drywall
  attenuation: 4.0
- start: [6.21, 7.02]
  end: [4.95, 7.02]
  floor: first
  room_names: [Airing Cupboard]
  material: drywall
  attenuation: 4.0
- start: [10.68, 9.18]
  end: [6.82, 9.18]
  floor: ground
  room_names: [Living Room, Dining Room]
  material: open
  attenuation: 0.0
- start: [4.37, 6]
  end: [4.37, 6]
  floor: ground
  room_names: [Hall]
  material: concrete
  attenuation: 13.5
- start: [1.9, 9.0]
  end: [1.9, 9.0]
  floor: first
  room_names: [Sophie Bedroom]
  material: drywall
  attenuation: 4.0
- start: [0, 9.06]
  end: [1.95, 9.06]
  floor: ground
  room_names: [Utility]
  material: concrete
  attenuation: 13.5
- start: [4.37, 3.24]
  end: [5.5, 3.24]
  floor: ground
  room_names: [Toilet, Shoe Cupboard]
  material: drywall
  attenuation: 4.0
- start: [5.5, 4.5]
  end: [5.5, 3.2]
  floor: ground
  room_names: [Shoe Cupboard]
  material: drywall
  attenuation: 4.0
- start: [7.85, 4.0]
  end: [7.85, 5.89]
  floor: first
  room_names: [En Suite]
  material: drywall
  attenuation: 4.0
- start: [7.85, 5.28]
  end: [7.85, 4.0]
  floor: first
  room_names: [Master Bedroom]
  material: drywall
  attenuation: 4.0
- start: [6.82, 13.32]
  end: [6.82, 6]
  floor: ground
  room_names: [Kitchen]
  material: open
  attenuation: 0.0
- start: [6.23, 0]
  end: [6.23, 5.28]
  floor: first
  room_names: [Master Bedroom]
  material: drywall
  attenuation: 4.0
- start: [6.21, 2.9]
  end: [4.09, 2.9]
  floor: first
  room_names: [Landing]
  material: drywall
  attenuation: 4.0
- start: [7.85, 5.89]
  end: [7.85, 5.28]
  floor: first
  room_names: [Spare Room Wardrobe]
  material: drywall
  attenuation: 4.0
- start: [1.95, 6.72]
  end: [1.95, 4.49]
  floor: ground
  room_names: [New Utility]
  material: osb_double
  attenuation: 12.0
- start: [6.21, 9.0]
  end: [10.7, 9.0]
  floor: first
  room_names: [Spare Room]
  material: drywall
  attenuation: 4.0
- start: [4.37, 6.8]
  end: [4.37, 3.24]
  floor: ground
  room_names: [Office]
  material: thermalite
  attenuation: 7.0
- start: [6.21, 5.89]
  end: [6.21, 9.0]
  floor: first
  room_names: [Spare Room]
  material: drywall
  attenuation: 4.0
- start: [7.85, 5.89]
  end: [7.85, 5.89]
  floor: first
  room_names: [En Suite]
  material: drywall
  attenuation: 4.0
- start: [6.21, 9.0]
  end: [6.21, 7.54]
  floor: first
  room_names: [Main Bathroom]
  material: drywall
  attenuation: 4.0
- start: [4.37, 1.91]
  end: [4.37, 3.24]
  floor: ground
  room_names: [Toilet, Garage]
  material: thermalite
  attenuation: 7.0
- start: [0, 4.49]
  end: [0, 6.72]
  floor: ground
  room_names: [New Utility]
  material: concrete
  attenuation: 13.5
- start: [7.85, 5.28]
  end: [6.21, 5.28]
  floor: first
  room_names: [Spare Room Wardrobe, Master Bedroom]
  material: drywall
  attenuation: 4.0
- start: [1.95, 6.8]
  end: [4.37, 6.8]
  floor: ground
  room_names: [Office, Kitchen]
  material: thermalite
  attenuation: 7.0
- start: [6.82, 6]
  end: [4.37, 6]
  floor: ground
  room_names: [Kitchen, Hall]
  material: thermalite
  attenuation: 7.0
- start: [6.21, 7.54]
  end: [4.08, 7.54]
  floor: first
  room_names: [Main Bathroom, Landing]
  material: drywall
  attenuation: 4.0
- start: [0, 1.91]
  end: [0, 4.49]
  floor: ground
  room_names: [Garage]
  material: concrete
  attenuation: 13.5
- start: [5.5, 1.9]
  end: [5.5, 4.5]
  floor: ground
  room_names: [Hall]
  material: drywall
  attenuation: 4.0
- start: [10.7, 4.0]
  end: [10.7, 0]
  floor: first
  room_names: [Master Bedroom]
  material: drywall
  attenuation: 4.0
- start: [6.82, 1.9]
  end: [5.5, 1.9]
  floor: ground
  room_names: [Hall]
  material: thermalite
  attenuation: 7.0
- start: [6.82, 9.18]
  end: [6.82, 13.32]
  floor: ground
  room_names: [Living Room]
  material: open
  attenuation: 0.0
- start: [6.82, 13.32]
  end: [10.68, 13.32]
  floor: ground
  room_names: [Living Room]
  material: thermalite
  attenuation: 7.0
- start: [10.7, 0]
  end: [6.23, 0]
  floor: first
  room_names: [Master Bedroom]
  material: drywall
  attenuation: 4.0
- start: [4.95, 7.02]
  end: [4.95, 7.54]
  floor: first
  room_names: [Airing Cupboard]
  material: drywall
  attenuation: 4.0
- start: [4.09, 6.0]
  end: [4.09, 2.9]
  floor: first
  room_names: [Noah Bedroom]
  material: drywall
  attenuation: 4.0
- start: [1.95, 6.8]
  end: [1.95, 13.32]
  floor: ground
  room_names: [Kitchen]
  material: thermalite
  attenuation: 7.0
- start: [4.37, 3.2]
  end: [4.37, 4.5]
  floor: ground
  room_names: [Shoe Cupboard]
  material: thermalite
  attenuation: 7.0
- start: [10.7, 9.0]
  end: [10.7, 5.89]
  floor: first
  room_names: [Spare Room]
  material: drywall
  attenuation: 4.0
- start: [0, 6.72]
  end: [0, 9.06]
  floor: ground
  room_names: [Utility]
  material: concrete
  attenuation: 13.5
- start: [6.21, 7.54]
  end: [6.21, 7.02]
  floor: first
  room_names: [Airing Cupboard]
  material: drywall
  attenuation: 4.0
- start: [1.9, 2.9]
  end: [1.9, 6.0]
  floor: first
  room_names: [Noah Bedroom]
  material: drywall
  attenuation: 4.0
- start: [4.08, 9.0]
  end: [4.08, 9.0]
  floor: first
  room_names: [Main Bathroom]
  material: drywall
  attenuation: 4.0
- start: [10.7, 4.0]
  end: [7.85, 4.0]
  floor: first
  room_names: [En Suite, Master Bedroom]
  material: drywall
  attenuation: 4.0
- start: [6.21, 9.0]
  end: [6.21, 9.0]
  floor: first
  room_names: [Spare Room]
  material: drywall
  attenuation: 4.0
- start: [4.37, 4.5]
  end: [5.5, 4.5]
  floor: ground
  room_names: [Shoe Cupboard, Hall]
  material: drywall
  attenuation: 4.0
- start: [4.09, 2.9]
  end: [4.09, 7.54]
  floor: first
  room_names: [Landing]
  material: drywall
  attenuation: 4.0
- start: [6.21, 5.89]
  end: [6.21, 5.89]
  floor: first
  room_names: [Spare Room Wardrobe]
  material: drywall
  attenuation: 4.0
- start: [6.82, 5.71]
  end: [6.82, 9.18]
  floor: ground
  room_names: [Dining Room]
  material: open
  attenuation: 0.0
- start: [10.7, 9.18]
  end: [10.7, 5.71]
  floor: ground
  room_names: [Dining Room]
  material: open
  attenuation: 0.0
- start: [7.85, 5.89]
  end: [10.7, 5.89]
  floor: first
  room_names: [En Suite]
  material: drywall
  attenuation: 4.0
- start: [1.95, 13.32]
  end: [6.82, 13.32]
  floor: ground
  room_names: [Kitchen]
  material: concrete
  attenuation: 13.5
- start: [1.95, 9.06]
  end: [1.95, 6.72]
  floor: ground
  room_names: [Utility]
  material: drywall
  attenuation: 4.0
- start: [1.9, 9.0]
  end: [4.08, 9.0]
  floor: first
  room_names: [Sophie Bedroom]
  material: drywall
  attenuation: 4.0
- start: [6.21, 7.54]
  end: [6.21, 2.9]
  floor: first
  room_names: [Landing]
  material: drywall
  attenuation: 4.0
- start: [10.7, 5.71]
  end: [10.7, 0]
  floor: ground
  room_names: [Lounge]
  material: concrete
  attenuation: 13.5
- start: [10.68, 13.32]
  end: [10.68, 9.18]
  floor: ground
  room_names: [Living Room]
  material: concrete
  attenuation: 13.5
- start: [4.09, 7.54]
  end: [4.09, 7.54]
  floor: first
  room_names: [Landing]
  material: drywall
  attenuation: 4.0
- start: [4.08, 9.0]
  end: [6.21, 9.0]
  floor: first
  room_names: [Main Bathroom]
  material: drywall
  attenuation: 4.0
- start: [1.9, 6.0]
  end: [1.9, 9.0]
  floor: first
  room_names: [Sophie Bedroom]
  material: drywall
  attenuation: 4.0
- start: [4.08, 9.0]
  end: [4.08, 6.0]
  floor: first
  room_names: [Sophie Bedroom]
  material: drywall
  attenuation: 4.0
- start: [6.21, 5.89]
  end: [7.85, 5.89]
  floor: first
  room_names: [Spare Room Wardrobe]
  material: drywall
  attenuation: 4.0
- start: [10.7, 5.89]
  end: [6.21, 5.89]
  floor: first
  room_names: [Spare Room]
  material: drywall
  attenuation: 4.0
- start: [4.08, 7.54]
  end: [4.08, 9.0]
  floor: first
  room_names: [Main Bathroom]
  material: drywall
  attenuation: 4.0
- start: [4.95, 7.54]
  end: [6.21, 7.54]
  floor: first
  room_names: [Airing Cupboard]
  material: drywall
  attenuation: 4.0
- start: [10.7, 5.89]
  end: [10.7, 4.0]
  floor: first
  room_names: [En Suite]
  material: drywall
  attenuation: 4.0
- start: [5.5, 1.91]
  end: [4.37, 1.91]
  floor: ground
  room_names: [Toilet]
  material: concrete
  attenuation: 13.5
- start: [5.5, 3.24]
  end: [5.5, 1.91]
  floor: ground
  room_names: [Toilet]
  material: drywall
  attenuation: 4.0
- start: [10.7, 0]
  end: [6.82, 0]
  floor: ground
  room_names: [Lounge]
  material: concrete
  attenuation: 13.5
  ```

My floorplan for reference. I was playing around writing an external calibrator using bayesian optimisation to train an ML model, but it got out of hand trying to cater for all the different variances. While playing, my optimiser did improve the accuracy to some degree, but due to the nature of how walls are actually used in the companion code, this would result in far more error on the floorplan.

![image](https://github.com/user-attachments/assets/677d58ee-2fad-4528-b1db-3e3c8183e02d)

**Comment by erkr** [comment]
I really would love this feature! Some remarks:

- Adding the materials section is nice (maybe include thickness, just for drawing them in the map).
- BUT please keep it more simple and optionally add wall types as part of the existing room definitions. Example:

```
    rooms: 
      - name: entree
        points:
          - [ 0, 11.5, drywall]
          - [ 1.8, 11.5]  # default wall settings (as today)
          - [ 1.8, 10.1, concrete]
          - [ 0, 10.1, open]
          - [ 0, 11.5, concrete]
```
