### ISSUE TITLE
Node Z position?

### ISSUE THREAD

**Issue by chrisgilldc** [ESPresense/ESPresense-companion#955]
Good morning!
I want to clarify how a node's Z position gets set.
The documentation says the node's point should be its x,y,z position within a room.
I have a four-story row house and when the 3D visualization got added, I found it was showing all my nodes on the first floor. 
The documentation says that a node's position x,y,z is relative to the room it's in.
Thus, if I have a floor and room defined this way:

```
  - id: second
    name: Second Floor
    bounds: [[0,0,3], [12, 12, 6]]
    rooms:
      - name: Dining Room
        points:
          - [0, 0]
          - [0, 3.363]
          - [5.789, 3.363]
          - [5.789, 0]
```

and nodes there defined this way:

```
nodes:
  - name: dining_east
    point: [0.1016, 0.2413, 1.702]
    room: Dining Room
    floors: ["second"]
  - name: dining_west
    point: [5.7912, 2, 0.5]
    room: Dining Room
    floors: ["second"]
```

Then it should put `dining_east` at a total height of 4.702m and `dining_west` at a total height of 3.05m.

My question is, is the nodes being displayed incorrectly a visualization problem, or a manifestation of a deeper problem with incorrect height calculation? Has anyone else seen this?

Thanks.
