### ISSUE TITLE
GPS latitude and longitude way off

### ISSUE THREAD

**Issue by erkr** [ESPresense/ESPresense-companion#982]
The offset added to the GPS coordinates (based on X, Y) are way off. Especially for the longitude, less then 1 meters X translates in ca 100 meters west! That is 100 times too far and I thing in the wrong direction (+1 X should move east?)

configured longitude:
```
gps:
  latitude: 51.xxxxxxxxxxxx
  longitude: 5.53972737852905
  elevation: 20
```

sensor:
```
latitude: 51.xxxxxxxxxxxxxx
longitude: 5.539828776574977
gps_accuracy: 0
elevation: 21.12941920696853
x: 0.870960921201916
"y": 7.037361072328212
z: 1.129419206968532
```

The latitude is probably calculated right, but I guess the calculation of the longitude calculation doesn't correctly for the latitude.
For my area the correction should be ca 0.000014776097465839 per meter
